# Generated by Django 3.2 on 2022-12-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to='uploads')),
                ('isi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Buku',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to='uploads')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kategori')),
            ],
            options={
                'verbose_name_plural': 'Artikel',
            },
        ),
    ]
