# Generated by Django 3.2 on 2022-12-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_trendingmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingmovie',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
