# Generated by Django 3.2 on 2022-12-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_trendingmovie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingmovie',
            name='adult',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='original_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='popularity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='vote_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
