# Generated by Django 3.2 on 2022-12-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_popularmovie_topratedmovie_tvairingtoday_tvpopular_tvtoprated_upcomingmovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tvairingtoday',
            new_name='tvairingtodaymovie',
        ),
        migrations.RenameModel(
            old_name='tvpopular',
            new_name='tvpopularmovie',
        ),
        migrations.RenameModel(
            old_name='tvtoprated',
            new_name='tvtopratedmovie',
        ),
    ]
