# Generated by Django 3.2 on 2022-12-12 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_bokmarktrending'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bookmark', models.CharField(blank=True, max_length=100, null=True)),
                ('adult', models.CharField(blank=True, max_length=100, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_language', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', models.TextField()),
                ('popularity', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('vote_count', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='bokmarktrending',
        ),
    ]
