# Generated by Django 3.2 on 2022-12-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20221212_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buku',
        ),
        migrations.DeleteModel(
            name='bookmark',
        ),
    ]
