# Generated by Django 4.1.3 on 2022-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('A', 'Action'), ('C', 'Comedy'), ('D', 'Drama'), ('H', 'Horror'), ('R', 'Romance')], max_length=1)),
                ('language', models.CharField(choices=[('E', 'English'), ('I', 'Indonesia')], max_length=1)),
                ('status', models.CharField(choices=[('R', 'Released'), ('C', 'Coming Soon')], max_length=1)),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
