# Generated by Django 3.2 on 2022-12-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_whatclist'),
    ]

    operations = [
        migrations.CreateModel(
            name='trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('overview', models.TextField()),
            ],
        ),
    ]
