# Generated by Django 3.2 on 2022-12-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='id_trend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
