# Generated by Django 3.2 on 2022-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_trending_id_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatclist',
            name='id_whatch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
