# Generated by Django 3.2 on 2022-12-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_whatclist_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='trending',
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
